package adapter

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/kagent-dev/kagent/go/api/agentplugin"
	"github.com/kagent-dev/kagent/go/harness/codex/config"
)

// renderCodexConfig emits the complete user-level config for the selected
// CODEX_HOME. It never merges an existing config file: compiler output and the
// adapter mode are the only configuration authorities.
func renderCodexConfig(cfg config.Config, workspace, codexHome, skillsRoot string) ([]byte, error) {
	var result bytes.Buffer
	result.WriteString("# Generated by kagent. Manual changes are replaced.\n")
	writeScalar(&result, "model", cfg.Model)
	writeScalar(&result, "model_provider", cfg.ModelProvider)
	if cfg.ReasoningEffort != "" {
		writeScalar(&result, "model_reasoning_effort", cfg.ReasoningEffort)
	}
	if cfg.DeveloperInstructions != "" {
		writeScalar(&result, "developer_instructions", cfg.DeveloperInstructions)
	}
	writeScalar(&result, "web_search", "disabled")
	result.WriteString("check_for_update_on_startup = false\n")
	if cfg.Provider == nil {
		// The enrolled host authenticates this isolated per-slot home through
		// `codex login`. Pin the file store so the runtime reads auth.json from
		// that exact home instead of selecting an ambient OS keyring policy.
		writeScalar(&result, "cli_auth_credentials_store", "file")
		writeScalar(&result, "default_permissions", externalPermissionProfile)
	}

	credentialEnvironment := map[string]string{
		"KAGENT_CONFIG_JSON":         "exclude",
		"KAGENT_AGENT_CARD_JSON":     "exclude",
		config.DefaultAPIKeyEnv:      "exclude",
		config.DefaultAccessTokenEnv: "exclude",
		"OPENAI_BASE_URL":            "exclude",
		"OPENAI_ORGANIZATION":        "exclude",
		"OPENAI_ORG_ID":              "exclude",
		"OPENAI_PROJECT":             "exclude",
		"OPENAI_PROJECT_ID":          "exclude",
	}
	if cfg.Provider != nil {
		credentialEnvironment[cfg.Provider.APIKeyEnv] = "exclude"
	}
	for _, server := range cfg.MCPServers {
		for _, value := range server.Headers {
			if environmentName, ok := config.HeaderEnvironment(value); ok {
				credentialEnvironment[environmentName] = "exclude"
			}
		}
	}
	result.WriteString("\n[shell_environment_policy]\ninherit = \"core\"\nignore_default_excludes = false\n")
	fmt.Fprintf(&result, "filters = %s\n", tomlStringMap(credentialEnvironment))
	result.WriteString("\n[apps._default]\nenabled = false\n")
	// The semantic A2A adapter does not yet represent Codex collaboration
	// events. Disable the stable-by-default feature instead of dropping those
	// side effects on the floor.
	result.WriteString("\n[features]\nmulti_agent = false\n")
	if cfg.Provider == nil {
		fmt.Fprintf(&result, "\n[permissions.%s]\n", tomlString(externalPermissionProfile))
		writeScalar(&result, "description", "YourOwn.Chat owner-authorized host-read local Codex agent")
		fmt.Fprintf(&result, "\n[permissions.%s.filesystem]\n", tomlString(externalPermissionProfile))
		// Native preview mode keeps host reads available for owner-selected local
		// tools while proving exact denies for the subscription credential files.
		// A hardened release still requires an admin-owned requirements ceiling.
		fmt.Fprintf(&result, "%s = %s\n", tomlString("/"), tomlString("read"))
		fmt.Fprintf(&result, "%s = %s\n", tomlString(workspace), tomlString("write"))
		for _, path := range []string{
			filepath.Join(codexHome, "auth.json"),
			filepath.Join(codexHome, ".credentials.json"),
			filepath.Join(codexHome, ".env"),
		} {
			fmt.Fprintf(&result, "%s = %s\n", tomlString(path), tomlString("deny"))
		}
		fmt.Fprintf(&result, "\n[permissions.%s.workspace_roots]\n", tomlString(externalPermissionProfile))
		fmt.Fprintf(&result, "%s = true\n", tomlString(workspace))
		fmt.Fprintf(&result, "\n[permissions.%s.network]\nenabled = false\n", tomlString(externalPermissionProfile))
	}

	if cfg.Provider != nil {
		fmt.Fprintf(&result, "\n[model_providers.%s]\n", tomlString(cfg.ModelProvider))
		writeScalar(&result, "name", cfg.Provider.Name)
		writeScalar(&result, "base_url", cfg.Provider.BaseURL)
		writeScalar(&result, "env_key", cfg.Provider.APIKeyEnv)
		writeScalar(&result, "wire_api", "responses")
		result.WriteString("requires_openai_auth = false\n")
	}

	// Untrusted project scope prevents a checked-out repository from adding a
	// second .codex/config.toml layer over the compiler-owned user config.
	fmt.Fprintf(&result, "\n[projects.%s]\ntrust_level = \"untrusted\"\n", tomlString(workspace))

	serverNames := sortedMapKeys(cfg.MCPServers)
	for _, name := range serverNames {
		server := cfg.MCPServers[name]
		fmt.Fprintf(&result, "\n[mcp_servers.%s]\n", tomlString(name))
		writeScalar(&result, "url", server.URL)
		result.WriteString("required = true\n")
		writeScalar(&result, "default_tools_approval_mode", "approve")
		if len(server.Tools) != 0 {
			fmt.Fprintf(&result, "enabled_tools = %s\n", tomlStringArray(server.Tools))
		}
		if server.StartupTimeoutMS > 0 {
			fmt.Fprintf(&result, "startup_timeout_ms = %d\n", server.StartupTimeoutMS)
		}
		if server.ToolTimeoutSeconds > 0 {
			fmt.Fprintf(&result, "tool_timeout_sec = %d\n", server.ToolTimeoutSeconds)
		}
		staticHeaders := make(map[string]string)
		environmentHeaders := make(map[string]string)
		for header, value := range server.Headers {
			if environmentName, ok := config.HeaderEnvironment(value); ok {
				environmentHeaders[header] = environmentName
			} else {
				staticHeaders[header] = value
			}
		}
		if len(staticHeaders) != 0 {
			fmt.Fprintf(&result, "http_headers = %s\n", tomlStringMap(staticHeaders))
		}
		if len(environmentHeaders) != 0 {
			fmt.Fprintf(&result, "env_http_headers = %s\n", tomlStringMap(environmentHeaders))
		}
	}

	for _, name := range selectedSkillNames(cfg.SkillResources) {
		result.WriteString("\n[[skills.config]]\n")
		writeScalar(&result, "path", strings.TrimRight(skillsRoot, "/")+"/"+name)
		result.WriteString("enabled = true\n")
	}
	return result.Bytes(), nil
}

func writeScalar(target *bytes.Buffer, key, value string) {
	fmt.Fprintf(target, "%s = %s\n", key, tomlString(value))
}

func tomlString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(fmt.Sprintf("encode TOML string: %v", err))
	}
	return string(encoded)
}

func tomlStringMap(values map[string]string) string {
	keys := sortedMapKeys(values)
	entries := make([]string, 0, len(keys))
	for _, key := range keys {
		entries = append(entries, tomlString(key)+" = "+tomlString(values[key]))
	}
	return "{ " + strings.Join(entries, ", ") + " }"
}

func tomlStringArray(values []string) string {
	encoded := make([]string, 0, len(values))
	for _, value := range values {
		encoded = append(encoded, tomlString(value))
	}
	return "[" + strings.Join(encoded, ", ") + "]"
}

func sortedMapKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func selectedSkillNames(resources *agentplugin.Resources) []string {
	if resources == nil {
		return nil
	}
	names := make([]string, 0, len(resources.Skills)+len(resources.Plugins))
	for _, skill := range resources.Skills {
		names = append(names, skill.Name)
	}
	for _, plugin := range resources.Plugins {
		names = append(names, plugin.Skills...)
	}
	slices.Sort(names)
	return names
}
